# Generated by Django 5.0.6 on 2024-05-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
