# Generated by Django 5.0.6 on 2024-05-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='tbl_users',
        ),
    ]
