# Generated by Django 5.0.6 on 2024-06-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('id',)},
        ),
    ]
