# Generated by Django 5.0.6 on 2024-06-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('pk',)},
        ),
    ]
