# Generated by Django 5.0.6 on 2024-05-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='tbl_equipments',
        ),
    ]
