# Generated by Django 5.0.6 on 2024-05-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_equipment_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='nama',
            new_name='name',
        ),
    ]
